### ISSUE TITLE
Nondistinct user agent

### ISSUE THREAD

**Issue by Ironholds** [MatmaRex/Sunflower#1]
Per our API etiquette guidelines, the user agent for Sunflower should contain (at a minimum) a contact address/URL for the author(s).

**Comment by MatmaRex** [comment]
Sunflower complies with the [MediaWiki API etiquette](https://www.mediawiki.org/wiki/API:Etiquette#User-Agent_header) by providing application name in the user-agent field. If you want more than that, patches are welcome. Unfortunately I can't really spend time maintaining this library.

**Comment by tommorris** [comment]
Just sent in a pull request.

**Comment by MatmaRex** [comment]
Fixed in 89cd794be41e658cebf39509eb4a70b84cf6665f.
